runtime: php
env: flex

runtime_config:
  document_root: .

#[START env]
env_variables:
    # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
    # values obtained when configuring your Cloud SQL instance.
    MYSQL_USER: 'root'
    MYSQL_PASSWORD: '1234'
    MYSQL_DSN: "mysql:dbname=dbtest55;unix_socket=/cloudsql/test55-207804:asia-south1:test55"
#[END env]

#[START cloudsql_settings]
# Use the connection name obtained when configuring your Cloud SQL instance.
beta_settings:
    cloud_sql_instances: 'test55-207804:asia-south1:test55'
#[END cloudsql_settings]